---
- name: configure vagrant box for docker
  hosts: default
  sudo: True
  gather_facts: False
  tasks:
    - name: Add Docker repository key to keychain
      apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
    - name: Add Docker repository
      apt_repository: repo='deb https://get.docker.com/ubuntu docker main' update_cache=yes
    - name: install packages
      apt: name={{ item }}
      with_items:
        - lxc-docker
        - python-pip
    - name: install docker-py
      pip: name=docker-py

